---
# https://github.com/marketplace/actions/github-action-for-latex
name: build-latex-document
run-name: Build LaTeX document
on:
  push:
    paths:
      - 'tex/**'

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Set up Git repository
        uses: actions/checkout@v3

      - name: 📝 Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          root_file: proofs.tex

        # https://stackoverflow.com/a/58393457/8213085
      - name: ⬆️ Upload the PDF file
        run: |
          git config --global user.name 'Bill Wallis (GHA)'
          git config --global user.email 'bilbottom@users.noreply.github.com'
          git add --ignore-errors -- tex/proofs.pdf
          git commit --message "📝 docs: Compile LaTeX document"
          git push
